### ISSUE TITLE
Implement upstream echo response

### ISSUE THREAD

**Issue by rustamin** [juks/iso-8583-socket-queue#28]
Hallo,
I am trying to implement auto reply echo request from the ISO host. When the ISO host send echo request I got this upstream error:
```
2018-03-26 16:47:50 - info: Upstream error: ISO host sent data with no client connected! Ignoring...

ISO host says
================================================================================================

     [Echo Request]

     Message Type Indicator [0].......................0800
     Bitmap [1].......................................82200000000000000400000000000000
     Transmission Date and Time [7]...................0326094750
     System Trace Audit Number [11]...................018386
     Network Management Information Code [70].........301

================================================================================================
```

**Comment by juks** [comment]
It is not the same.

**Comment by juks** [comment]
Done.

**Comment by if414029** [comment]
Hello,
I have an error like that picture. Im trying to echo test
![tes](https://user-images.githubusercontent.com/23304103/49857425-11c26e00-fe25-11e8-8c95-69403fcc0747.png)

**Comment by juks** [comment]
Hi!

Please refer to this line of code: https://github.com/juks/SocketQueue/blob/ddbab6578559cd2ff2191c03615ea873f95fe9d3/lib/iso8583/lib/packager/smartVista.js#L21

There are some basic sets of fields that SQ expects for every known message type.

**Comment by if414029** [comment]
Thank you i have change that code.
But when i run my code in port 80, the server listen in tcp6 . and when i send the data i got error like this
![crop](https://user-images.githubusercontent.com/23304103/49915914-c498d780-feca-11e8-8c8c-fb5ff103911b.png)

**Comment by juks** [comment]
What happens is the upstream host closes the connection after it receives the message. This might be due to the fact it expects different message format or due to some other reason else. Checking the upstream log might help.

**Comment by if414029** [comment]
How to Checking the upstream log ?

**Comment by if414029** [comment]
But when i run the server, host to host connection refused to my server. But can access my ip server in their browser.
Host to host say they dont receive the message. The format that I made was in accordance with what the host to host needed and in accordance with the documentation

**Comment by juks** [comment]
What you might check:

- Do they have a connection even in their log;
- Is there any firewall in between;
- What happens if you send the payload using netcat like it is mentioned here https://github.com/juks/SocketQueue/blob/master/sample_payloads/readme.md;

**Comment by if414029** [comment]
Hi,
- How to check connection in their log?
- Yes, there is a firewall in between
-  To test the payload i just need to run that command line?

Thank you

**Comment by if414029** [comment]
The Host To Host run aplikasi visual basic, they dont have port? so how can i connect?
example if my port 80 listend as apache2 they can connect. but if i stop my apache and run the socket queue they can;t connet

**Comment by juks** [comment]
You should not use privileged port numbers (under 1024).

I am sorry, but I can't help with your specific setup. You need to engineer it yourself.

**Comment by if414029** [comment]
why i can't use privileged port numbers?
