### ISSUE TITLE
Virtual HSM module / HSM simulator for SQ

### ISSUE THREAD

**Issue by scalpovich** [juks/iso-8583-socket-queue#37]
Hi Igor,
Hope you're doing well.

It would be interesting to add a security module call HSM for Socket Queue. To manage security exchanges by sending u HSM commands for key verification. 

Did you think about that? Do get some directive / idea?

**Comment by juks** [comment]
Hi!

Since we have discussed this topic before (#30), could you please share some feedback of overall SQ operation experience and if there is any progress solving the HSM stuff since last year?

It is easier to find a way between two point when thay are already visible and reachable.
