### ISSUE TITLE
BCD packer

### ISSUE THREAD

**Issue by cavebring** [juks/iso-8583-socket-queue#47]
Hi,
I need a very common packer:

> Nx -x numeric digits, BCD encoded, right justified with leading half byte zero filled

So **831** would be **hex 08 31** 

All packers I use that does BCD does calculation wrong (or I am thinking wrong), but if I use packer **fixed-b** which is the only I can find that does BCD and I specify **length 6**, and data **999999** it does **hex 00 00 00 99 99 99**. So I was thinking that the length is in bytes, but when I change to **length 3** it instead does **00 09 99** which is so strange.

What I am expecting is that length 6, data 999999 is binary coded as hex 99 99 99, is there a current packer for this or do we need to add a BCD packer?

**Comment by juks** [comment]
Hi!

Great you have mentioned it. Had to do it before. Here is some types reference example. What your are looking for is **fixed-b**. You need two bytes of length.

```
$ node _help.js
Available types reference:
--------------------------

Input value: 123

Output:

a.js:                123
an.js:               123
anp.js:              123
ans.js:              123
b.js:                400
bitmap-hex.js:       123
bitmap.js:           123
fixed-b-hex.js:      123
fixed-b.js:          <Buffer 00 01 23>
fixed-char.js:       <Buffer 31 32 33>
fixed-hn.js:         <Buffer 00 00 01 23>
fixed-n.js:          123
ll-bin-char.js:      <Buffer 03 31 32 33>
ll-bin-hn.js:        <Buffer 03 01>
ll-bin-n.js:         <Buffer 03 31 32 33>
ll-char.js:          <Buffer 30 33 31 32 33>
ll-n.js:             03123
llan.js:             03123
llans.js:             3123
lll-bin-an.js:       123
lllan.js:            003123
lllans.js:           003123
lln.js:              03123
llns.js:              3123
n.js:                123
```

**Comment by cavebring** [comment]
Oh that's helpful. However in many ISO8583 93 implementations (I have two different in front of me) where both specifies BCD `x numeric digits, BCD encoded, right justified with leading half byte zero filled`.

So with that 

Input value: **123**
should Output: **<Buffer 01 23>**

Input value: **1234**
should Output: **<Buffer 12 34>**

Maybe we can do a packer **fixed-bcd.js**

Juks, is this something you would have time to add? Would be very appreciated!

**Comment by juks** [comment]
Sure, I can add new packers, this is the reason i am here. But please help me understand what is missing.

Right now, with fixed-b (yes, this might be not the perfect name):

**Input value 1234, length 2**
fixed-b.js:          <Buffer 12 34>

**Input value 12, length 2**
fixed-b.js:          <Buffer 00 12>

**Input value 1, length 1**
fixed-b.js:          <Buffer 01>

Could you please list the cases that are missing right now?

**Comment by cavebring** [comment]
You are right, I'm not missing anything, I have tested all thinkable scenarios and fixed-b acts according to BCD specs.

Would it be possible to add BCD packer to length header as well? In that case, where do I do that?

**Comment by cavebring** [comment]
Setting config.json:

```json
    "useHeader": true,
    "headerFormat": "length:fixed-b:2",
    "lengthIncludeHeader": false,
```

Throws error:

```js
buffer.js:208
    throw new ERR_INVALID_ARG_TYPE('value', 'not number', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "value" argument must not be of type number. Received type number
    at Function.from (buffer.js:208:11)
    at Object.pack (/home/ec2-user/iso-8583-socket-queue/lib/iso8583/lib/packager/elavon.js:502:19)
    at Object.length (/home/ec2-user/iso-8583-socket-queue/lib/iso8583/lib/packager/elavon.js:490:17)
    at Object.<anonymous> (/home/ec2-user/iso-8583-socket-queue/lib/iso8583/lib/packager/elavon.js:591:52)
    at Array.forEach (<anonymous>)
    at Object.getHeader (/home/ec2-user/iso-8583-socket-queue/lib/iso8583/lib/packager/elavon.js:589:25)
    at Iso8583Packet.getHeader (/home/ec2-user/iso-8583-socket-queue/lib/iso8583-packet/lib/iso8583Packet.js:280:42)
    at Iso8583Packet.getMessage (/home/ec2-user/iso-8583-socket-queue/lib/iso8583-packet/lib/iso8583Packet.js:258:38)
    at Iso8583Packet.getRawMessage (/home/ec2-user/iso-8583-socket-queue/lib/iso8583-packet/lib/iso8583Packet.js:266:34)
    at Socket.socket.processQueue (/home/ec2-user/iso-8583-socket-queue/lib/socketServer/lib/upstream.js:194:50)
```

Also there is something strange with BCD, because when testing the packing, like this it works:

```js
var iso8583 = require('../../../lib/iso8583');
var packager = new iso8583('mypacker');


var msg = {
    "0":"1804",
    "3":"000000",
    "11":"000001",
    "12":"191212164401",
    "24":"831"};

console.log('Original message: ');
console.log(msg);
console.log();

console.log('Parsed message fields: ');
var parsed = packager.packWithBinMask(msg);
console.log(parsed);
console.log();
```

But when sending to server (running the node service) it sends like this:

`2019-12-12 16:54:41 - verbose: [30 30 32 36 00 00 18 04 20 30 01 00 00 00 00 00 00 00 00 00 00 01 00 00 00 16 44 01 00 31]   `

**DE 24 - Input value 831, length 2**
fixed-b.js: <Buffer 00 31> should be <Buffer 08 31>

also this one:

**DE 12 - Input value 191212164401, length 6**
fixed-b.js: <Buffer 00 00 00 16 44 01> should be <Buffer 19 12 12 16 44 01>

**Comment by juks** [comment]
You may use the _--headerFormat="length:fixed-b:2"_ parameter for that. But please pull the source before.

Noticed that _fixed-b-hn_ format is redundant (will remove it later) and fixed an integer case problem in fixed-b.

**Comment by cavebring** [comment]
The header error is fixed  ✅

But this BCD error still exist, because when testing the packing, like this it works:

```js
var iso8583 = require('../../../lib/iso8583');
var packager = new iso8583('mypacker');


var msg = {
    "0":"1804",
    "3":"000000",
    "11":"000001",
    "12":"191212164401",
    "24":"831"};

console.log('Original message: ');
console.log(msg);
console.log();

console.log('Parsed message fields: ');
var parsed = packager.packWithBinMask(msg);
console.log(parsed);
console.log();
```

But when sending to server (running the node service) it sends like this:

`2019-12-12 16:54:41 - verbose: [30 30 32 36 00 00 18 04 20 30 01 00 00 00 00 00 00 00 00 00 00 01 00 00 00 16 44 01 00 31]   `

**DE 24 - Input value 831, length 2**
fixed-b.js: <Buffer 00 31> should be <Buffer 08 31>

also this one:

**DE 12 - Input value 191212164401, length 6**
fixed-b.js: <Buffer 00 00 00 16 44 01> should be <Buffer 19 12 12 16 44 01>

**Comment by juks** [comment]
Will handle it later today

**Comment by juks** [comment]
Did a serious types refactoring, improved the types reference help. Please check.

Also tried DE 24 in fixed-b mode, length 2: looks like no more problem.

**Comment by cavebring** [comment]
Unfortunately the error persists.

Data sent:
```json
{
	"0":"1804",
	"3":"000000",
	"11":"000001",
	"12":"191212164401",
	"24":"831"
}
```

Formats:

```js
  '0': {
    length: 2,
    name:   'Message Type Indicator',
    type:   'fixed-b',
    alias:  ''
  },
  '3': {
    length: 3,
    name:   'Processing Code',
    type:   'fixed-b',
    alias:  ''
  },
  '11': {
    length: 3,
    name:   'System Trace Audit Number',
    type:   'fixed-b',
    alias:  'stan'
  },
  '12': {
    length: 6,
    name:   'Time, Local Transaction',
    type:   'fixed-b',
    alias:  ''
  },
  '24': {
    length: 2,
    name:   'Function Code',
    type:   'fixed-b',
    alias:  ''
  
```

```txt
     [Echo Response]

     Message Type Indicator [0].......................04
     Bitmap [1].......................................2030010000000000
     Processing Code [3]..............................000
     System Trace Audit Number [11]...................001
     Time, Local Transaction [12].....................164401
     Function Code [24]...............................31

================================================================================================

                         
2019-12-13 11:10:12 - : Writing to queue http:::ffff [0]                         
2019-12-13 11:10:12 - : New queue item 0                         
2019-12-13 11:10:12 - : Processing queue [pending 1 / total 1]                         
2019-12-13 11:10:12 - : Queue keys dump: 0                         
2019-12-13 11:10:12 - : Upstreaming data for http:::ffff                         
2019-12-13 11:10:12 - : [.....0................D..1]                         
2019-12-13 11:10:12 - : [00 24 00 04 20 30 01 00 00 00 00 00 00 00 00 00 00 01 00 00 00 16 44 01 00 31]   
```


However, it works in this test script, which is strange:

```js
var iso8583 = require('../../../lib/iso8583');
var packager = new iso8583('mypacker');

var msg = {
    "0":"1804",
    "3":"888888",
    "11":"999999",
    "12":"191210230301",
    "24":"831"};

console.log('Original message: ');
console.log(msg);
console.log();

console.log('Parsed message fields: ');
var parsed = packager.packWithBinMask(msg);
console.log(parsed);
console.log();
```

```txt
Original message: 
{
  '0': '1804',
  '3': '888888',
  '11': '999999',
  '12': '191210230301',
  '24': '831'
}

Parsed message fields: 
<Buffer 18 04 88 88 88 99 99 99 19 12 10 23 03 01 08 31>
```

**Comment by juks** [comment]
This was a padding problem for hex field. Made a fix. Please check.

**Comment by cavebring** [comment]
Yes, it works, we can close this ✅

**Comment by juks** [comment]
Thanks!

**Comment by cavebring** [comment]
Do you know what we have forgot? The variable part of this.

**ll-b** data: "123456" **pack** should be <Buffer 03 12 34 56>
<Buffer 03 12 34 56>  **unpack** should be '123456'

**lll-b** data: "123456" **pack** should be <Buffer 00 03 12 34 56>
<Buffer 00 03 12 34 56>  **unpack** should be '123456'

**Comment by juks** [comment]
I can add it later.
