### ISSUE TITLE
Echo request initiated from SocketQueue every 5 minutes

### ISSUE THREAD

**Issue by cavebring** [juks/iso-8583-socket-queue#50]
So I have seen the implementation of responding to echo, but not generation of echo messages to HOST (without having any client connected).

In ISO8583 93 spec:

> 1804 Network Management Echo requests will be generated by the partner host system at a rate of one **every five minutes**. This is to verify the link integrity for diagnostic purposes only and will not affect the link status. These echo messages must not be sent at a frequency of more than one message every five minutes. Such messaging is optional if transactional data successfully traverses the H2H link since the previous 1804 / 1814 message exchange.

So we have to send echo messages if no other messages is sent within 5 minutes.

New feature or something that exists that can be modified?

**Comment by juks** [comment]
You can use the test client (https://github.com/juks/iso-8583-socket-queue#iso-host-emulation-and-self-test-clients). Just need to point to the upstream. It will send the given packages no matter it there were an exchange, but it is not a big overhead.

**Comment by cavebring** [comment]
I think I will add this feature and push it up to you. Would be good with this feature implemented.

Just give me some directions on the following:

* Is there any global object containing information about last transaction?
* Is there any global timer method that runs in the code I can append to?
* Which is the process that "owns and connects" to the host logic files?

**Comment by juks** [comment]
I thing a good way to start is to start with simple, then move on. The simble point could be in making some improvements to the test client, like configuration options for various packet types and fields. Now it is all hardcoded. Then provide some changeable options for the packet interval.

This will do the basic job: Every project maintainer will be able to set the interval and the payload being sent periodicaly.

The test client is here: https://github.com/juks/iso-8583-socket-queue/blob/master/lib/testSuite/lib/testClient.js.

The main logic for upstreaming the data is here: https://github.com/juks/iso-8583-socket-queue/blob/7f805f8e96e343b3b7e67035ba5112a70a02b587/lib/socketServer/lib/upstream.js#L211. But breaking in there really not worth of keeping one packet one 1 five minutes. There might be some degug complications. Ther should be a timer, and timer-related work and other stuff.

On my experience it was always accomplished by just sening this echo packet each X minutes no matter what. By the way, if the ISO host will close the connection — not a big deal, the queue will work fine, we'll reconnect, no packets will get lost.

**Comment by cavebring** [comment]
Yes, I think I will just add a timer and send a packet every 5 minute regardless of transactions or not. Will work something out. Thanks!

**Comment by cavebring** [comment]
I'm trying to access upstream socket from the host logic:

File: logic/myhost.js
```js
Iso8583Logic.prototype.upstreamEcho = function(stan) {
  
  var now = moment(new Date());
  var p = new iso8583Packet();
  p.setFields({
    0:   1804,
    3:   "000000",
    11:  stan,
    12:  now.format("YYMMDDHHmmss"),                    
    24:  831,
    32:  "01008600998"
  });

  this.upstream.socket.write(p); // <---- how do I reach socket for upstream in this function?
  
}
```

```txt
/Users/xxxxx/iso-8583-socket-queue/lib/iso8583/lib/logic/myhost.js:171
  this.socket.write(Buffer.concat(p));
              ^

TypeError: Cannot read property 'write' of undefined
    at Iso8583Logic.upstreamEcho (/Users/xxxxx/iso-8583-socket-queue/lib/iso8583/lib/logic/myhost.js:171:15)

```

**Comment by juks** [comment]
You can do _this.upstream.sendData(this, p)_;

**Comment by scalpovich** [comment]
Hi @cavebring 
I think we deal with same iso host system. I was made some customization in order to deal with my host to.
First you have to define the echotest iso logic in your global logic.
Then in the upstream.js, Try this for periodic  echo test:

`var echoTestTimout = 300000; // 300000 correspond to 5min in ms`

>      
             var echoTest = parent.logic.sentUpstreamEcho();
               dd('Key exchange ok ...Sent first echo test request to Upstream ....' , 'verbose');
               dd('-----------------' + echoTest.pretty(), 'verbose');
          if (echoTest) this.write(echoTest.getMessage({
                                      staticHeader: global.c['useStaticHeader'],
                                      lengthHeader: global.c['useLengthHeader']
                                  }));
              setTimeout(function() {
            dd('Sent echo test request to Upstream ..../5min after..' , 'verbose');
            dd('-----------------' + echoTest.pretty(), 'verbose');
           if (echoTest)  this.write(echoTest.getMessage({
              staticHeader: global.c['useStaticHeader'],
              lengthHeader: global.c['useLengthHeader']
            }));
            }.bind(this)
              , echoTestTimout);

**Comment by cavebring** [comment]
Lovely, thank you @scalpovich !
