### ISSUE TITLE
how to config format message as 2 byte length + TPDU + BITMAP + DATA

### ISSUE THREAD

**Issue by cesc1802** [juks/iso-8583-socket-queue#52]
I have got used two parameters lengthIncludeHeader and useHeader but when I send msg "00 36 60 00 10 00 00 08 00 20 38 01 00 00 80 00 00 92 00 00 00 00 19 08 29 06 07 02 00 68 33 37 31 30 30 30 31 33". i cannot parse this msg. pls help me config. thanks

**Comment by juks** [comment]
Hi!

The message you provided looks to be correct: 2 bytes length header value is 36 (2 for header, 34 for the message body).

Maybe you need other header format? Or maybe epected length value should not include header?
