### ISSUE TITLE
Authentication on connection start

### ISSUE THREAD

**Issue by sarriaroman** [juks/iso-8583-socket-queue#54]
Is there any way to send an authentication message when the connection is established? The provider I need to connect requires to send a Connector ID when the connection is established before start sending messages between the parts.

Thanks! Awesome job by the way :)

**Comment by juks** [comment]
Hi!

Auth (logon, logoff) messages are considered to be of x8xx message type (Network Management Message). The actual data elements may depend on specific host implementation.

**Comment by sarriaroman** [comment]
Sorry to bother, but do you have any examples of logon/logoff messages? I really want to use NodeJS for the implementation and I can't find information about it.

**Comment by juks** [comment]
Each system implemetation has its own data elements specification. You need to get the docs for the one you need to integrate with.

**Comment by sarriaroman** [comment]
Sorry about the delay on my answer. I need to send a message before the first message on the Channel with an identification number. If I don't send that number everything I send gets rejected by the other side because I'm not identified. Sorry about such a newbie question :(

**Comment by juks** [comment]
Please check this method: https://github.com/juks/iso-8583-socket-queue/blob/6e4ae5eff82af2dcc465bf84e60761bbeab23dfb/lib/iso8583/lib/logic/smartVista.js#L81

You now can define a packet that will be sent exactly each time the connection is being established.

**Comment by sarriaroman** [comment]
Awesome @juks ! I will try with that!
