### ISSUE TITLE
iso20022 support

### ISSUE THREAD

**Issue by scalpovich** [juks/iso-8583-socket-queue#55]
Hi Juks,
Its will be important to add in **enhancement** of this package a possibility to onvert iso8583 to new iso20022.
We can work on it together

**Comment by juks** [comment]
Hi!

ISO20022 seems to be XML format. Need to get some real use cases first. Does somebody really needs to convert with external gateway?

**Comment by scalpovich** [comment]
Hi,
ISO858 also based on XML, right?
Simple use case can be a payment system based on iso8583 who want to deal with newest financial iso20022 system

**Comment by juks** [comment]
ISO8583 is the specification of binary protocol for slow communication lines. XML is easy to understand and human-readable but the payback is a significant payload overhead compared to ISO8583.

I mean real life example.

**Comment by scalpovich** [comment]
Get it,
but what do mean by payback is a significant payload overhead compared to ISO8583?
