### ISSUE TITLE
New Feature Request: Add Agent Proxy

### ISSUE THREAD

**Issue by ronaldotantra** [juks/iso-8583-socket-queue#58]
Hi, It would be nice to add proxy agent option on connection to upstreamhost. Is it possible ?

**Comment by juks** [comment]
Hi!

Could you, please, describe in more details?

**Comment by ronaldotantra** [comment]
I want to connect to upstream host through proxy. I see you use net module to build this socket queue. Based on what I read net have no proxy support.
Is it possible to configure or change the net in this socket queue to connect upstream host through proxy?

**Comment by juks** [comment]
But why not just using a port forwarding? Proxy means many hosts behind one host. HTTP proxy understands what host to connect by a 'host' header. In case of ISO8583 there is no host identifier in a single message.
