### ISSUE TITLE
error while trying https JSON request

### ISSUE THREAD

**Issue by melawa2017** [juks/iso-8583-socket-queue#60]
hi Igor ,
Kindly assist in below error  , I had tried to run the server on 8080 based on your instructions 
command 1: 
node socketQueue.js --upstreamHost=10.0.0.1 --upstreamPort=5000 --listenHttpPort=8080 --vv --logFile=log.txt

command 2:
curl -H "Content-Type: application/json" -X POST -d '{ "0": "0200",  "3": "0",  "4": 1000,  "7": "0818160933",  "11": 618160,  "12": "150820130600",  "22": "056",  "24": "200",  "25": "00",  "35": "4850781234567891=19082012232800000037",  "41": 992468,  "42": 124642124643,  "49": "810",  "55": "9f2608571f1e10d4fa4aac9f2701809f100706010a03a4b8029f37045bb074729f3602000c950500800010009a031508189c01009f02060000000010005f2a02064382023c009f1a0206439f03060000000000009f3303e0f0c89f34034403029f3501229f1e0835313230323831358407a00000000310109f41030000565f340101" }' http://localhost:8080

**the error i got : 

curl: (3) [globbing] unmatched close brace/bracket in column 1
{"result":"","errors":["SyntaxError: Unexpected token ' in JSON at position 0"]}**

**Comment by melawa2017** [comment]
when i tried by POSTMAN  i got the below error: 

{
    "result": "",
    "errors": [
        "Packet is expired!"
    ]
}

**Comment by juks** [comment]
Hi. I guess this is not the curl command you have actually used. The one you provided here is fine. There is no issue here.

Packet expiration is determined by the field 7 value.
