### ISSUE TITLE
Listening to host messages from socket queue

### ISSUE THREAD

**Issue by xwiz** [juks/iso-8583-socket-queue#62]
Hi, wonderful and important project. I have a question, in the scenario where we need to forward messages from the ISO host to a http service to obtain and send back a response instantly to the host, is there a performance optimal way you would recommend? Is it okay to modify the [upstream listener](https://github.com/juks/iso-8583-socket-queue/blob/master/lib/socketServer/lib/upstream.js#L223)? `on data` event to do this? Thanks

**Comment by juks** [comment]
Hi! There should be no performance issues while you are using non-blocking methods. So if you modify the upstream logic so that is will forward every message received - it should work fine.

**Comment by xwiz** [comment]
Thank you @juks
