### ISSUE TITLE
Processing Code [3]..............................NaN

### ISSUE THREAD

**Issue by zarkozs** [juks/iso-8583-socket-queue#64]
Dear Juks,

thanks for all the efforts in this project

please note after implement the code, while the POS is trying to connect i got the below Error
2021-04-15 12:26:29 - verbose: ::ffff:192.168.250.45:61152: Warning! Iso8583 packet contains errors. Won't queue!
================================================================================================

     [ <faulty>]

     Message Type Indicator [0].......................0074
     Bitmap [1].......................................30***03072340580
     Processing Code [3]..............................NaN
     Amount, Transaction [4]..........................5***97200000
     System Trace Audit Number [11]...................032800
     Time, Local Transaction [12].....................000000000001
     Date, Expiration [14]............................4
     Track 2 Data [35]................................122509015568210
     Response code [39]...............................415
     Amount, Fees [46]................................121221200051400009990001595             368
     Additional amounts [54]..........................

================================================================================================
Errors:
     Field 3 expected to be numeric
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

your support is highly appreciated

thanks

Zar

**Comment by juks** [comment]
Hi!

You need to adjust the headers format and the iso8583 setup (https://github.com/juks/iso-8583-socket-queue/blob/master/lib/iso8583/lib/packager/smartVista.js) according to your system configuration.
