### ISSUE TITLE
Communication Link Using SocketQueue

### ISSUE THREAD

**Issue by bobozar** [juks/iso-8583-socket-queue#65]
Hello Juks and the SQ team,

I'm new to this ISO8583 standardisation and I have a few questions.  Can SocketQueue be used as the middle server to forward request/data from Bank Host to Fintech Host vice versa?

We want to integrate with a bank, and they said, their **_module accepts (socket to socket communication) the financial transaction based on the ISO8583-1993 specification. At the front of ISO8583 message is placed message length in hex format and header._**

In this case, can I use SQ to forward request/data from bank host through SQ to fintech client also from fintech host to bank client through SQ?

I hope you get my point?

**Comment by juks** [comment]
Hi!

Yes, SQ was ment to act like this: be a fintech gateway to the Bank ISO host. No problem using it this way with default or adopted iso8583 config.
